/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import client.Client;
import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.util.List;
import java.util.NoSuchElementException;
import java.util.Observable;
import java.util.Observer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.text.BadLocationException;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

/**
 *
 * @author simon
 */
public class GUI extends javax.swing.JFrame implements Observer {

    Client theClient;

    static String userName;
    static String ip;
    static int port;

    static StyledDocument doc;

    static Style boldBlue;
    static Style normalBlack;
    static Style italicPurple;
    static Style boldBrown;
    static Style boldBlack;
    static Style gray;

    static DefaultListModel listModel = new DefaultListModel();

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        boldBlue = jTextPane1.addStyle("Im a bold blue Style", null);
        normalBlack = jTextPane1.addStyle("Im a normal black Style", null);
        italicPurple = jTextPane1.addStyle("Im a italic purple Style", null);
        boldBlack = jTextPane1.addStyle("Im a bold black Style", null);
        gray = jTextPane1.addStyle("Im a grey Style", null);

        doc = jTextPane1.getStyledDocument();

        StyleConstants.setForeground(boldBlue, Color.BLUE);
        StyleConstants.setBold(boldBlue, true);

        StyleConstants.setForeground(normalBlack, Color.BLACK);
        StyleConstants.setItalic(normalBlack, true);

        StyleConstants.setForeground(italicPurple, new Color(102, 0, 102));
        StyleConstants.setBold(italicPurple, true);

        StyleConstants.setForeground(boldBlack, Color.BLACK);
        StyleConstants.setBold(boldBlack, true);

        StyleConstants.setForeground(gray, Color.GRAY);

        jTextPane1.setEditable(false);

        if (userName == null) {

            userName = JOptionPane.showInputDialog("Please enter your user name:");
            if (userName == null) {
                System.exit(1);
            }
        }
        
        if (ip == null) {

            ip = JOptionPane.showInputDialog("Please enter the server's ip address:");
            if (ip == null) {
                System.exit(1);
            }
        }
        
        if (port == -1) {
            String tmpPort = JOptionPane.showInputDialog("Please enter the server's port:");
            port = Integer.parseInt(tmpPort);
            if (port == -1) {
                System.exit(1);
            }
        }
        

        theClient = new Client(ip, port, userName, this);
        String responseText = "";
        // try to get the next message from the server
        // however we will only receive it if the username gets accepted
        

        String tokens[] = responseText.split("#");

        if (tokens[0].equals("USERLIST")) {
            String userNames[] = tokens[1].split(",");

            listModel.clear();

            for (String userName : userNames) {
                 // if the user is not known by the map of styles (with colors)
                // add a style to the userftp://ftp.simonsteinaa.dk/public_html/

                listModel.addElement(userName);
            }

        }

        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                try {
                    theClient.stop();
                } catch (IOException ex) {
                    Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
        jTextField1.requestFocus();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(jTextPane1);

        jList1.setModel(listModel);
        jScrollPane2.setViewportView(jList1);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("Send");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("CHAT ROOM");

        jLabel2.setText("Enter message and press Enter or press Send");

        jLabel3.setText("User logged in");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        send();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        send();
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void send() {
        String theText = jTextField1.getText();
        theClient.send(theText);

        String receivers = "ALL";

        if (!theText.equals("")) {

            List<String> selectedUsers = jList1.getSelectedValuesList();
            // if none is selected - just assume we want to send the message to everybody
            if (selectedUsers.isEmpty()) {
                theClient.send("MSG#*#" + theText);
            } else {
                receivers = "";
                String sendString = "MSG#";
                for (String user : selectedUsers) {
                    sendString += user + ",";

                }
                // get rid of the last ,
                sendString = sendString.substring(0, sendString.length() - 1);
                receivers = sendString.split("#")[1];
                sendString = sendString + "#" + theText;

                theClient.send(sendString);
            }

            // insert the user's message to his own window
            try {
                doc.insertString(doc.getLength(), "(" + userName, italicPurple);
                doc.insertString(doc.getLength(), " to " + receivers, gray);
                doc.insertString(doc.getLength(), "): ", italicPurple);
                doc.insertString(doc.getLength(), theText + "\n", boldBlack);
            } catch (BadLocationException e) {

            }

            jTextField1.setText("");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        port = -1;
        ip = null;
        userName = null;
        switch (args.length) {
            case 3:
                userName = args[2];
            case 2:
                port = Integer.parseInt(args[0]);
                ip = args[1];

                break;
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {

        String responseText = (String) arg;
        String tokens[] = responseText.split("#");

        String display = "";

        if (tokens[0].equals("USERLIST")) {
            String userNames[] = tokens[1].split(",");
            listModel.clear();

            for (String userName : userNames) {

                listModel.addElement(userName);
                // if the user is not known by the map of styles (with colors)
                // add a style to the user
//                if (!users.containsKey(userName)) {
//                    users.put(userName, getStyleWithRandomColor());
//                }
            }

        }
        if (tokens[0].equals("MSG")) {

            // we only want it displayed if it is not coming from ourselves!
            if (!tokens[1].equals(userName)) {
                try {
                    // user.get(tokens[1]) returns some random Style with a random color
                    doc.insertString(doc.getLength(), "(" + tokens[1] + "): ", normalBlack);
                    doc.insertString(doc.getLength(), tokens[2] + "\n", normalBlack);
                } catch (BadLocationException e) {
                }
            }

        }

    }
}
